### ISSUE TITLE
assertion failed (yes I have the model files in the correct place)

### ISSUE THREAD

**Issue by jaysonh** [kylemcdonald/ofxFaceTracker#146]
I've made an app using ofxFaceTracker and it runs fine on my computer, but when I try running it on a clients computer they get an error:

Assertion failed (s.is_open()), function Load, file /Applications/of_v0.9.8_osx_release/addons/ofxFaceTracker/libs/FaceTracker/src/lib/Tracker.c line 59

seems like it is still pointing to the local facetracker lib path for my computer, even though it's running on theirs.

Any ideas?

**Comment by kylemcdonald** [comment]
Sorry, the only reason the `s.is_open()` fails is because the model files are in the wrong place.

Error messages may show paths from the computer the code was compiled on, but that doesn't mean the code is looking in the wrong place.

I recommend creating an ofDirectory and listing the contents of the data folder. That will give you some indication of what's going wrong.

**Comment by jaysonh** [comment]
Hi kyle thanks for the response. Putting the data folder inside of the contents/resources folder of the executable fixed the problem, and then setting the root path with  ofSetDataPathRoot("../Resources/data/");
